import type { ComparisonOption, ItineraryItem, Trip, UserProfile } from "@/types/domain";

export const mockProfile: UserProfile = {
  id: "8cbf89cb-37e0-47f2-9b7f-aac985b40e80",
  full_name: "Rama Pradana",
  whatsapp_number: "+6281234567890",
  role: "user",
  points_balance: 620,
  lifetime_points: 1120,
  loyalty_tier: "adventurer",
};

export const mockTrips: Trip[] = [
  {
    id: "trip_01",
    user_id: mockProfile.id,
    public_id: "bali-healing-7n8k",
    status: "draft",
    payment_status: "paid",
    planning_fee_idr: 149000,
    is_group_trip: true,
    is_surprise_mode: false,
    intake_data: {
      who: "2 dewasa + 1 anak",
      vibe: "healing + culinary",
      when: "12-16 April 2026",
      where: "Bali",
      budget: "IDR 15.000.000 total",
      pacing: "balanced",
      specialNeeds: "vegetarian",
    },
    selected_comparison_option: 2,
    total_est_cost_idr: 12850000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "trip_02",
    user_id: mockProfile.id,
    public_id: "lombok-surprise-9dd2",
    status: "intake",
    payment_status: "paid",
    planning_fee_idr: 99000,
    is_group_trip: false,
    is_surprise_mode: true,
    intake_data: {
      who: "2 pasangan",
      vibe: "surprise",
      when: "Mei 2026, 4D3N",
      budget: "IDR 7.000.000",
      pacing: "slow",
    },
    selected_comparison_option: null,
    total_est_cost_idr: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockComparisonOptions: ComparisonOption[] = [
  {
    id: "opt_1",
    trip_id: "trip_01",
    option_number: 1,
    summary: {
      title: "Bali Hemat Pantai Selatan",
      destinationHighlights: ["Sanur", "Uluwatu", "Nusa Dua"],
      vibeTags: ["budget", "healing", "pantai"],
      estimatedBudgetIdr: 10500000,
      rationale: "Fokus akomodasi hemat dengan spot sunset terbaik dan kuliner lokal.",
    },
    is_selected: false,
  },
  {
    id: "opt_2",
    trip_id: "trip_01",
    option_number: 2,
    summary: {
      title: "Bali Balanced Family Escape",
      destinationHighlights: ["Ubud", "Canggu", "Seminyak"],
      vibeTags: ["balanced", "family", "culinary"],
      estimatedBudgetIdr: 12850000,
      rationale: "Kombinasi santai, aktivitas keluarga, dan pengalaman makan terkurasi.",
    },
    is_selected: true,
  },
  {
    id: "opt_3",
    trip_id: "trip_01",
    option_number: 3,
    summary: {
      title: "Bali Premium Retreat",
      destinationHighlights: ["Ubud", "Nusa Penida", "Jimbaran"],
      vibeTags: ["premium", "wellness", "romantic"],
      estimatedBudgetIdr: 17600000,
      rationale: "Upgrade resort dan pengalaman private tour untuk trip lebih eksklusif.",
    },
    is_selected: false,
  },
];

export const mockItineraryItems: ItineraryItem[] = [
  {
    id: "item_01",
    trip_id: "trip_01",
    day_number: 1,
    time_slot: "morning",
    sort_order: 1,
    activity_type: "transport",
    vendor_id: null,
    title: "Arrival + Airport Transfer",
    description: "Penjemputan di DPS dan check-in ke villa Ubud.",
    tips: "Siapkan eSIM sebelum mendarat.",
    est_cost_idr: 350000,
    location_lat: -8.7482,
    location_lng: 115.1672,
    location_address: "Ngurah Rai Airport",
    status: "booked_flexible",
    source: "internal_db",
    booking_url: null,
    booking_ref: "TRF-8891",
  },
  {
    id: "item_02",
    trip_id: "trip_01",
    day_number: 1,
    time_slot: "afternoon",
    sort_order: 2,
    activity_type: "dining",
    vendor_id: null,
    title: "Late Lunch at Sayan",
    description: "Menu plant-based friendly dengan view sawah.",
    tips: "Booking 1 hari sebelumnya.",
    est_cost_idr: 420000,
    location_lat: -8.5101,
    location_lng: 115.244,
    location_address: "Ubud",
    status: "draft",
    source: "web_search",
    booking_url: "https://example.com/sayan-lunch",
    booking_ref: null,
  },
  {
    id: "item_03",
    trip_id: "trip_01",
    day_number: 2,
    time_slot: "morning",
    sort_order: 1,
    activity_type: "attraction",
    vendor_id: null,
    title: "Tegalalang Rice Terrace Walk",
    description: "Jalan santai 90 menit sebelum ramai.",
    tips: "Bawa topi dan cash untuk donasi jalan.",
    est_cost_idr: 150000,
    location_lat: -8.431,
    location_lng: 115.279,
    location_address: "Tegallalang",
    status: "booked_locked",
    source: "internal_db",
    booking_url: null,
    booking_ref: "ATK-9910",
  },
];

export const mockPackingList = [
  { item: "Sunblock SPF 50", category: "Essentials", checked: true },
  { item: "Sandal anti-slip", category: "Clothing", checked: false },
  { item: "Reusable water bottle", category: "Essentials", checked: false },
  { item: "Obat anti mabuk", category: "Health", checked: false },
];
