-- Migration 012: Seed Indonesian vendors for grounding itinerary generation

INSERT INTO public.vendors (
  name,
  type,
  city,
  province,
  price_tier,
  avg_rating,
  is_verified,
  location_lat,
  location_lng,
  tags
)
VALUES
  ('Alaya Resort Ubud', 'hotel', 'Ubud', 'Bali', 'premium', 4.8, true, -8.5069, 115.2625, ARRAY['romantic', 'nature', 'spa']),
  ('Komaneka at Bisma', 'hotel', 'Ubud', 'Bali', 'premium', 4.9, true, -8.5124, 115.2614, ARRAY['luxury', 'valley view', 'healing']),
  ('The Layar', 'villa', 'Seminyak', 'Bali', 'premium', 4.7, true, -8.6874, 115.1570, ARRAY['private pool', 'romantic', 'beach']),
  ('Svarga Loka Resort', 'hotel', 'Ubud', 'Bali', 'mid', 4.5, true, -8.5178, 115.2692, ARRAY['family', 'pool', 'rice terrace']),
  ('ZEN Rooms Kuta', 'hotel', 'Kuta', 'Bali', 'budget', 3.9, true, -8.7217, 115.1686, ARRAY['budget', 'central', 'beach access']),
  ('Plataran Borobudur', 'hotel', 'Magelang', 'Jawa Tengah', 'premium', 4.8, true, -7.6047, 110.2037, ARRAY['heritage', 'romantic', 'temple view']),
  ('Phoenix Hotel Yogyakarta', 'hotel', 'Yogyakarta', 'DIY', 'mid', 4.3, true, -7.7957, 110.3658, ARRAY['heritage', 'central', 'cultural']),
  ('The 101 Yogyakarta Tugu', 'hotel', 'Yogyakarta', 'DIY', 'mid', 4.4, true, -7.7876, 110.3636, ARRAY['central', 'family', 'cultural']),
  ('Aston Lombok Beach Resort', 'hotel', 'Senggigi', 'Nusa Tenggara Barat', 'mid', 4.2, true, -8.4892, 116.0492, ARRAY['beach', 'family', 'sunset']),
  ('Cocotinos Sekotong', 'hotel', 'Sekotong', 'Nusa Tenggara Barat', 'mid', 4.6, true, -8.7681, 115.9387, ARRAY['secluded', 'snorkeling', 'nature']),
  ('Locavore', 'restaurant', 'Ubud', 'Bali', 'premium', 4.9, true, -8.5147, 115.2615, ARRAY['fine dining', 'local ingredients', 'romantic']),
  ('Warung Babi Guling Ibu Oka', 'restaurant', 'Ubud', 'Bali', 'budget', 4.7, true, -8.5059, 115.2622, ARRAY['local', 'babi guling', 'authentic']),
  ('Merah Putih Restaurant', 'restaurant', 'Seminyak', 'Bali', 'premium', 4.6, true, -8.6812, 115.1556, ARRAY['indonesian', 'fine dining', 'cocktails']),
  ('Naughty Nuri''s Warung', 'restaurant', 'Ubud', 'Bali', 'mid', 4.5, true, -8.5201, 115.2640, ARRAY['ribs', 'casual', 'social']),
  ('Gudeg Yu Djum', 'restaurant', 'Yogyakarta', 'DIY', 'budget', 4.8, true, -7.7883, 110.3761, ARRAY['gudeg', 'local', 'breakfast', 'authentic']),
  ('Jejamuran', 'restaurant', 'Yogyakarta', 'DIY', 'mid', 4.6, true, -7.7419, 110.3836, ARRAY['mushroom', 'vegetarian friendly', 'unique']),
  ('Bebek Goreng Pak Ndut', 'restaurant', 'Yogyakarta', 'DIY', 'budget', 4.4, true, -7.8039, 110.3658, ARRAY['local', 'duck', 'authentic']),
  ('RM Sate Kelinci Pak Pong', 'restaurant', 'Wonosobo', 'Jawa Tengah', 'budget', 4.5, true, -7.3634, 109.9002, ARRAY['satay', 'local', 'authentic']),
  ('Cafe Jepun Bali', 'restaurant', 'Kuta', 'Bali', 'mid', 4.3, true, -8.7189, 115.1701, ARRAY['breakfast', 'casual', 'vegetarian']),
  ('Sardine Restaurant', 'restaurant', 'Seminyak', 'Bali', 'premium', 4.7, true, -8.6801, 115.1582, ARRAY['seafood', 'romantic', 'rice paddy']),
  ('Tegalalang Rice Terrace', 'attraction', 'Ubud', 'Bali', 'budget', 4.6, true, -8.4314, 115.2788, ARRAY['rice terrace', 'instagram', 'nature']),
  ('Tanah Lot Temple', 'attraction', 'Tabanan', 'Bali', 'budget', 4.7, true, -8.6213, 115.0868, ARRAY['temple', 'sunset', 'cultural']),
  ('Borobudur Temple', 'attraction', 'Magelang', 'Jawa Tengah', 'budget', 4.9, true, -7.6079, 110.2038, ARRAY['heritage', 'sunrise', 'UNESCO']),
  ('Prambanan Temple', 'attraction', 'Yogyakarta', 'DIY', 'budget', 4.8, true, -7.7520, 110.4914, ARRAY['heritage', 'Hindu', 'UNESCO']),
  ('Mount Bromo', 'attraction', 'Probolinggo', 'Jawa Timur', 'mid', 4.9, true, -7.9425, 112.9530, ARRAY['volcano', 'sunrise', 'adventure']),
  ('Nusa Penida Kelingking Beach', 'attraction', 'Nusa Penida', 'Bali', 'budget', 4.8, true, -8.7514, 115.4571, ARRAY['cliff', 'instagram', 'scenic']),
  ('Kuta Beach', 'attraction', 'Kuta', 'Bali', 'budget', 4.2, true, -8.7183, 115.1686, ARRAY['beach', 'surf', 'sunset']),
  ('Goa Gajah (Elephant Cave)', 'attraction', 'Ubud', 'Bali', 'budget', 4.4, true, -8.5235, 115.2878, ARRAY['temple', 'historical', 'cultural']),
  ('Malioboro Street', 'attraction', 'Yogyakarta', 'DIY', 'budget', 4.5, true, -7.7931, 110.3656, ARRAY['shopping', 'batik', 'cultural', 'street food']),
  ('Keraton Yogyakarta', 'attraction', 'Yogyakarta', 'DIY', 'budget', 4.6, true, -7.8056, 110.3642, ARRAY['heritage', 'sultanate', 'cultural']),
  ('Ubud Monkey Forest Trekking', 'experience', 'Ubud', 'Bali', 'budget', 4.3, true, -8.5185, 115.2585, ARRAY['wildlife', 'nature', 'walking']),
  ('Balinese Cooking Class Paon Bali', 'experience', 'Ubud', 'Bali', 'mid', 4.8, true, -8.5127, 115.2611, ARRAY['cooking', 'cultural', 'hands-on']),
  ('White Water Rafting Ayung River', 'experience', 'Ubud', 'Bali', 'mid', 4.6, true, -8.5342, 115.2342, ARRAY['adventure', 'river', 'group']),
  ('Batik Workshop Yogyakarta', 'experience', 'Yogyakarta', 'DIY', 'budget', 4.7, true, -7.8021, 110.3649, ARRAY['craft', 'cultural', 'hands-on']),
  ('Sunrise Merapi Jeep Tour', 'experience', 'Yogyakarta', 'DIY', 'mid', 4.8, true, -7.5410, 110.4457, ARRAY['adventure', 'volcano', 'sunrise', 'jeep']),
  ('Wayang Kulit Performance Sonobudoyo', 'experience', 'Yogyakarta', 'DIY', 'budget', 4.5, true, -7.8012, 110.3638, ARRAY['traditional', 'cultural', 'night']),
  ('Snorkeling Menjangan Island', 'experience', 'Buleleng', 'Bali', 'mid', 4.7, true, -8.1184, 114.5228, ARRAY['snorkeling', 'marine', 'nature']),
  ('Komodo Dragon Tour', 'experience', 'Labuan Bajo', 'Nusa Tenggara Timur', 'mid', 4.9, true, -8.4540, 119.8896, ARRAY['wildlife', 'unique', 'boat']),
  ('Sanur-Nusa Penida Fast Boat (Mola Mola Express)', 'transport', 'Sanur', 'Bali', 'mid', 4.4, true, -8.6775, 115.2628, ARRAY['fast boat', 'Nusa Penida', 'reliable']),
  ('Blue Bird Taxi Bali', 'transport', 'Denpasar', 'Bali', 'budget', 4.3, true, -8.6705, 115.2126, ARRAY['taxi', 'metered', 'reliable']),
  ('Grab Yogyakarta', 'transport', 'Yogyakarta', 'DIY', 'budget', 4.2, true, -7.7971, 110.3688, ARRAY['ride-hailing', 'affordable', 'app']),
  ('Perama Tour Bus Bali-Lombok', 'transport', 'Denpasar', 'Bali', 'budget', 3.9, true, -8.6705, 115.2126, ARRAY['tourist bus', 'ferry', 'budget']),
  ('Bluebird Limousine Airport Transfer', 'transport', 'Denpasar', 'Bali', 'mid', 4.5, true, -8.7382, 115.1669, ARRAY['airport', 'ac', 'reliable']),
  ('Made Bali Private Tour Guide', 'guide', 'Ubud', 'Bali', 'mid', 4.9, true, -8.5069, 115.2625, ARRAY['English', 'Balinese culture', 'flexible']),
  ('Yogyakarta Local Guide Pak Slamet', 'guide', 'Yogyakarta', 'DIY', 'budget', 4.8, true, -7.7971, 110.3688, ARRAY['Bahasa Indonesia', 'history', 'temple'])
;
